/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { StatsRequestBuilderRequestsMetadata, type StatsRequestBuilder } from './stats/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Dashboard
 */
export interface DashboardRequestBuilder extends BaseRequestBuilder<DashboardRequestBuilder> {
    /**
     * The stats property
     */
    get stats(): StatsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DashboardRequestBuilderUriTemplate = "{+baseurl}/Dashboard";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DashboardRequestBuilderNavigationMetadata: Record<Exclude<keyof DashboardRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    stats: {
        requestsMetadata: StatsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
