/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithEnumsListGetResponse}
 */
// @ts-ignore
export function createWithEnumsListGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithEnumsListGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithEnumsListGetResponse(withEnumsListGetResponse: Partial<WithEnumsListGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithEnumsListGetResponse(writer: SerializationWriter, withEnumsListGetResponse: Partial<WithEnumsListGetResponse> | undefined | null = {}) : void {
    if (withEnumsListGetResponse) {
        writer.writeAdditionalData(withEnumsListGetResponse.additionalData);
    }
}
export interface WithEnumsListGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/**
 * Builds and executes requests for operations under /enums/{enumsList}
 */
export interface WithEnumsListItemRequestBuilder extends BaseRequestBuilder<WithEnumsListItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithEnumsListGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WithEnumsListGetResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithEnumsListItemRequestBuilderUriTemplate = "{+baseurl}/enums/{enumsList}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithEnumsListItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithEnumsListItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWithEnumsListGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
