/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ProfileRequestBuilderRequestsMetadata, type ProfileRequestBuilder } from './profile/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /donor
 */
export interface DonorRequestBuilder extends BaseRequestBuilder<DonorRequestBuilder> {
    /**
     * The profile property
     */
    get profile(): ProfileRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DonorRequestBuilderUriTemplate = "{+baseurl}/donor";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DonorRequestBuilderNavigationMetadata: Record<Exclude<keyof DonorRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    profile: {
        requestsMetadata: ProfileRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
