/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetDashboardStatsResponseFromDiscriminatorValue, type GetDashboardStatsResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Dashboard/stats
 */
export interface StatsRequestBuilder extends BaseRequestBuilder<StatsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetDashboardStatsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<StatsRequestBuilderGetQueryParameters> | undefined) : Promise<GetDashboardStatsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StatsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface StatsRequestBuilderGetQueryParameters {
    loggedUserId?: string;
}
/**
 * Uri template for the request builder.
 */
export const StatsRequestBuilderUriTemplate = "{+baseurl}/Dashboard/stats{?loggedUserId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createGetDashboardStatsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
