/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithWilayaItemRequestBuilder, WithWilayaItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /communes
 */
export interface CommunesRequestBuilder extends BaseRequestBuilder<CommunesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.communes.item collection
     * @param wilayaId Unique identifier of the item
     * @returns {WithWilayaItemRequestBuilder}
     */
     byWilayaId(wilayaId: number) : WithWilayaItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CommunesRequestBuilderUriTemplate = "{+baseurl}/communes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CommunesRequestBuilderNavigationMetadata: Record<Exclude<keyof CommunesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWilayaId: {
        requestsMetadata: WithWilayaItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["wilayaId"],
    },
};
/* tslint:enable */
/* eslint-enable */
