/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBtcItemRequestBuilder, WithBtcItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Subscriptions/btc
 */
export interface BtcRequestBuilder extends BaseRequestBuilder<BtcRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Subscriptions.btc.item collection
     * @param btcId Unique identifier of the item
     * @returns {WithBtcItemRequestBuilder}
     */
     byBtcId(btcId: string) : WithBtcItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BtcRequestBuilderUriTemplate = "{+baseurl}/Subscriptions/btc";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BtcRequestBuilderNavigationMetadata: Record<Exclude<keyof BtcRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBtcId: {
        requestsMetadata: WithBtcItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["btcId"],
    },
};
/* tslint:enable */
/* eslint-enable */
