/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListBloodDonationRequestsResponseFromDiscriminatorValue, type ListBloodDonationRequestsResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /BloodDonationRequests
 */
export interface BloodDonationRequestsRequestBuilder extends BaseRequestBuilder<BloodDonationRequestsRequestBuilder> {
     subscribed: any;
     matching: any;
     nearby: any;
     post(requestData: any): unknown;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListBloodDonationRequestsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<BloodDonationRequestsRequestBuilderGetQueryParameters> | undefined) : Promise<ListBloodDonationRequestsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<BloodDonationRequestsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface BloodDonationRequestsRequestBuilderGetQueryParameters {
    filter?: string;
    level?: number;
    loggedUserId?: string;
}
/**
 * Uri template for the request builder.
 */
export const BloodDonationRequestsRequestBuilderUriTemplate = "{+baseurl}/BloodDonationRequests{?filter*,level*,loggedUserId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const BloodDonationRequestsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BloodDonationRequestsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createListBloodDonationRequestsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
