/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithEnumsListItemRequestBuilder, WithEnumsListItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /enums
 */
export interface EnumsRequestBuilder extends BaseRequestBuilder<EnumsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.enums.item collection
     * @param enumsList Unique identifier of the item
     * @returns {WithEnumsListItemRequestBuilder}
     */
     byEnumsList(enumsList: string) : WithEnumsListItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnumsRequestBuilderUriTemplate = "{+baseurl}/enums";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnumsRequestBuilderNavigationMetadata: Record<Exclude<keyof EnumsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byEnumsList: {
        requestsMetadata: WithEnumsListItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["enumsList"],
    },
};
/* tslint:enable */
/* eslint-enable */
