/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListWilayasResponseFromDiscriminatorValue, type ListWilayasResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Wilayas
 */
export interface WilayasRequestBuilder extends BaseRequestBuilder<WilayasRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListWilayasResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ListWilayasResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WilayasRequestBuilderUriTemplate = "{+baseurl}/Wilayas";
/**
 * Metadata for all the requests in the request builder.
 */
export const WilayasRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WilayasRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createListWilayasResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
