/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListCommunesEndpointResponseFromDiscriminatorValue, type ListCommunesEndpointResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /communes/{wilayaId}
 */
export interface WithWilayaItemRequestBuilder extends BaseRequestBuilder<WithWilayaItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListCommunesEndpointResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ListCommunesEndpointResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithWilayaItemRequestBuilderUriTemplate = "{+baseurl}/communes/{wilayaId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithWilayaItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithWilayaItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createListCommunesEndpointResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
